### ISSUE TITLE
Fait attention à ton `.gitgnore`

### ISSUE THREAD

**Issue by idris-maps** [JeanHerbaut/DataVis#2]
Tu as "commit" le dossier [node_modules](https://github.com/JeanHerbaut/DataVis/tree/master/20200228/node_modules)

efface le, commit et ajoute

```
20200228/node_modules
20200228/dist
```

à ton fichier `.gitignore`.

Après tu peux retourner dans `20200228` et refaire `npm install`

**Comment by JeanHerbaut** [comment]
Bonjour, 

Merci pour vos retours. 

Salutations, 

Jean Herbaut

De : Idris
Envoyé le :mardi, 3 mars 2020 18:43
À : JeanHerbaut/DataVis
Cc : Subscribed
Objet :[JeanHerbaut/DataVis] Fait attention à ton `.gitgnore` (#2)

Tu as "commit" le dossier node_modules
ajoute
20200228/node_modules

20200228/dist

à ton fichier .gitignore
